#!/bin/sh -e

. $(dirname $0)/config

curl -O https://distfiles.adelielinux.org/adelie/apk-tools-static/x86_64.apk
tar -xzOf x86_64.apk sbin/apk.static > /tmp/apk.static
chmod a+x /tmp/apk.static

mkdir -p "$NEWROOT"/etc/apk
/tmp/apk.static -X "https://distfiles.adelielinux.org/adelie/current/system" --root "$NEWROOT" --initdb --no-progress add adelie-core bash-binsh musl-dev gcc binutils

cd "$NEWROOT"

mount -t proc none proc
mount -t sysfs none sys
mount -R /dev dev
mount -R /run run
ln -s /run/shm dev/shm
mkdir ./$CLONE_DIR
mount -B $CLONE_DIR ./$CLONE_DIR
chroot "$NEWROOT" useradd -m -c "Travis User" -s /bin/sh -G wheel -u $SUDO_UID $SUDO_USER
